#ifndef __MIB_UNION_SHARE_H
#define __MIB_UNION_SHARE_H

#include "autoconf.h"
#include "linux/autoconf.h"

#define MAX_NOTICE_MAC_LIST 256 /*需要提醒的mac*/
#define MAX_FRIEND_NUM 64 /*备注mac*/
#define NOTICE_BAND_ALL  0xffffffff
#define MAX_NAME_LEN 31

#define MAX_FREE_EXP_LIST 1024
#define UTT_PHONE_LEN 11
#define UTT_PASS_LEN 20
#define UTT_PPPOE_NAME_LEN 31
#define IP_GROUP_NAME_LEN  31 
#define UTT_PPPOE_CLI_NAME_LEN UTT_PPPOE_NAME_LEN
#define UTT_PPPOE_CLI_PASS_LEN 31
#define UTT_INST_NAME_LEN 12
#define UTT_MAC_STR_LEN 20
#define UTT_3G_DEV_LEN 20
#define UTT_3G_LEN 31

#define UTT_TIME_LEN 6
#define UTT_DATE_LEN 10
#define UTT_USER_LEN	31
#define UTT_PASSWD_LEN	32
#define UTT_REMARK_LEN	31

#define UTT_INTERFACE_LEN 20
#define UTT_HOST_LEN	31

#define UTT_SSID_LENTH  32
#define UTT_PSK_PASSWD_LEN   63
#define UTT_PAS_KEY_VALUE_LEN 26
#define UTT_SEL_AUTHMODE_LEN 14
#define UTT_RADIUS_KEY_LEN 31
#define UTT_AP_IFNAME_LEN 7
#define UTT_AP_BS_LEN 20
#define UTT_WDS_MACLIST_LEN 128
#define UTT_WDS_MODE_LEN 5
#define UTT_DHCP_POOL_LEN 12

#define UTT_DDNS_PROVIDER_LEN 13 /* iplink.com.cn */
#define UTT_DDNS_HOST_LEN 31
#define UTT_DDNS_ACCOUNT_LEN 31
#define UTT_DDNS_PASSWD_LEN 63

#define MAX_FILTER_LEN 35

#define UTT_SZONE_LENTH  32
#define UTT_SSID_NUM    6

#define UTT_SW_VERSION_LEN  32
#define UTT_HW_VERSION_LEN  12
#define UTT_SW_MODEL_LEN    12
#define UTT_SW_NAME_LEN	    100

typedef struct st_mib_head {
    char name[UTT_INST_NAME_LEN + 1];
    int active;
}mibHead;

#define SLOT_NUMBER_ANY                0
typedef struct slotnumber {
    Word                                slotNumber;
} SlotNumber;



#if (CONFIG_USER_GOAHEAD_LANG_ZHCN == FYES)

#define DEFAULTPDBNAME133	"禁止QQ邮箱"
#define DEFAULTPDBNAME2		"禁止MSN"
#define DEFAULTPDBNAME3		"禁止阿里旺旺登陆"	
#define DEFAULTPDBNAME4		"禁止网页QQ"
#define DEFAULTPDBNAME5		"禁止飞信"
#define DEFAULTPDBNAME6		"禁止比特彗星、精灵"
#define DEFAULTPDBNAME7		"禁止迅雷搜索资源"
#define DEFAULTPDBNAME8		"禁止QQLive"
#define DEFAULTPDBNAME9		"禁止pps播放视频"
#define DEFAULTPDBNAME10	"禁止酷狗搜索资源"
#define DEFAULTPDBNAME11	"禁止pplive播放视频"
#define DEFAULTPDBNAME12	"禁止快播"
#define DEFAULTPDBNAME13	"禁止百度影音"
#define DEFAULTPDBNAME14	"禁止证券网站"
#define DEFAULTPDBNAME15	"禁止优酷网"
#define DEFAULTPDBNAME16	"禁止土豆网"
#define DEFAULTPDBNAME17	"禁止爱奇艺"
#define DEFAULTPDBNAME18	"禁止搜狐视频"
#define DEFAULTPDBNAME19	"禁止迅雷看看"
#define DEFAULTPDBNAME20	"禁止酷6"
#define DEFAULTPDBNAME21	"禁止56网"
#define DEFAULTPDBNAME22	"禁止新浪视频"
#define DEFAULTPDBNAME23	"禁止腾讯视频"
#define DEFAULTPDBNAME24	"禁止CNTV视频"
#define DEFAULTPDBNAME25	"禁止凤凰视频"
#define DEFAULTPDBNAME26	"禁止暴风影音"
#define DEFAULTPDBNAME27	"禁止激动网"
#define DEFAULTPDBNAME28	"禁止PPS"
#define DEFAULTPDBNAME29	"禁止风行"
#define DEFAULTPDBNAME30	"禁止游戏网站"
#define DEFAULTPDBNAME31	"禁止QQGame"
#define DEFAULTPDBNAME32	"禁止泡泡堂游戏"
#define DEFAULTPDBNAME33	"禁止征途"
#define DEFAULTPDBNAME34	"禁止完美世界，诛仙"
#define DEFAULTPDBNAME35	"禁止梦幻西游游戏"
#define DEFAULTPDBNAME36	"禁止劲舞团"
#define DEFAULTPDBNAME37	"禁止进入浩方"
#define DEFAULTPDBNAME38	"禁止魔兽世界"
#define DEFAULTPDBNAME39	"禁止永恒之塔"
#define DEFAULTPDBNAME40	"禁止跑跑卡丁车"
#define DEFAULTPDBNAME41	"禁止穿越火线"
#define DEFAULTPDBNAME46	"禁止龙之谷"
#define DEFAULTPDBNAME47	"禁止神仙传"
#define DEFAULTPDBNAME48	"禁止传奇"
#define DEFAULTPDBNAME49	"禁止天龙八部3"
#define DEFAULTPDBNAME50	"禁止反恐精英OL"
#define DEFAULTPDBNAME52	"禁止冒险岛"
#define DEFAULTPDBNAME53	"禁止倩女幽魂"
#define DEFAULTPDBNAME54	"禁止问道"
#define DEFAULTPDBNAME55	"禁止梦三国"
#define DEFAULTPDBNAME56	"禁止坦克世界"
#define DEFAULTPDBNAME57	"禁止淘宝网"
#define DEFAULTPDBNAME58	"禁止淘宝商城"
#define DEFAULTPDBNAME59	"禁止京东商城"
#define DEFAULTPDBNAME60	"禁止当当网"
#define DEFAULTPDBNAME61	"禁止卓越网"
#define DEFAULTPDBNAME62	"禁止拍拍网"
#define DEFAULTPDBNAME63	"禁止阿里巴巴"
#define DEFAULTPDBNAME64	"禁止麦考林"
#define DEFAULTPDBNAME65	"禁止hao123折扣"
#define DEFAULTPDBNAME66	"禁止凡客诚品"
#define DEFAULTPDBNAME67	"禁止唯品会"
#define DEFAULTPDBNAME68	"禁止聚尚网"
#define DEFAULTPDBNAME69	"禁止走秀网"
#define DEFAULTPDBNAME70	"禁止时尚起义"
#define DEFAULTPDBNAME71	"禁止梦芭莎购物"
#define DEFAULTPDBNAME72	"禁止银泰网"
#define DEFAULTPDBNAME73	"禁止V+服饰"
#define DEFAULTPDBNAME74	"禁止玛莎玛索"
#define DEFAULTPDBNAME75	"禁止太平鸟"
#define DEFAULTPDBNAME76	"禁止苏宁易购"
#define DEFAULTPDBNAME77	"禁止国美电器"
#define DEFAULTPDBNAME78	"禁止易迅网"
#define DEFAULTPDBNAME79	"禁止库巴购物网"
#define DEFAULTPDBNAME80	"禁止新蛋网"
#define DEFAULTPDBNAME81	"禁止绿森数码"
#define DEFAULTPDBNAME82	"禁止好乐买"
#define DEFAULTPDBNAME83	"禁止乐淘"
#define DEFAULTPDBNAME84	"禁止优购网"
#define DEFAULTPDBNAME85	"禁止名鞋库"
#define DEFAULTPDBNAME86	"禁止麦包包"
#define DEFAULTPDBNAME87	"禁止乐蜂网"
#define DEFAULTPDBNAME88	"禁止天天网"
#define DEFAULTPDBNAME89	"禁止丝芙网"
#define DEFAULTPDBNAME90	"禁止DHC化妆品"
#define DEFAULTPDBNAME91	"禁止金象大药房"
#define DEFAULTPDBNAME92	"禁止草莓网"
#define DEFAULTPDBNAME93	"禁止嗨淘网"
#define DEFAULTPDBNAME94	"禁止果皮网"
#define DEFAULTPDBNAME95	"禁止草莓派"
#define DEFAULTPDBNAME96	"禁止红孩子"
#define DEFAULTPDBNAME97	"禁止母婴之家"
#define DEFAULTPDBNAME98	"禁止一号店"
#define DEFAULTPDBNAME99	"禁止我买网"
#define DEFAULTPDBNAME100	"禁止拉手网"
#define DEFAULTPDBNAME101	"禁止糯米网"
#define DEFAULTPDBNAME102	"禁止美团网"
#define DEFAULTPDBNAME103	"禁止高朋网"
#define DEFAULTPDBNAME104	"禁止窝窝团"
#define DEFAULTPDBNAME105	"禁止QQ空间"
#define DEFAULTPDBNAME106	"禁止人人网"
#define DEFAULTPDBNAME107	"禁止朋友网"
#define DEFAULTPDBNAME108	"禁止新浪微博"
#define DEFAULTPDBNAME109	"禁止kaixin001"
#define DEFAULTPDBNAME110	"禁止51.com"
#define DEFAULTPDBNAME111	"禁止豆瓣"
#define DEFAULTPDBNAME112	"禁止淘米"
#define DEFAULTPDBNAME113	"禁止腾讯微博"
#define DEFAULTPDBNAME114	"禁止佳缘网"
#define DEFAULTPDBNAME115	"禁止淘江湖"
#define DEFAULTPDBNAME116	"禁止白社会"
#define DEFAULTPDBNAME117	"禁止珍爱网"
#define DEFAULTPDBNAME118	"禁止百合网"
#define DEFAULTPDBNAME119	"禁止爱情公寓"
#define DEFAULTPDBNAME120	"禁止多玩"
#define DEFAULTPDBNAME121	"禁止百度游戏"
#define DEFAULTPDBNAME122	"禁止37玩"
#define DEFAULTPDBNAME123	"禁止256G"
#define DEFAULTPDBNAME124	"禁止一游"
#define DEFAULTPDBNAME125	"禁止昆仑在线"
#define DEFAULTPDBNAME126	"禁止4399小游戏"
#define DEFAULTPDBNAME127	"禁止pps游戏平台"
#define DEFAULTPDBNAME128	"禁止7k7k小游戏"
#define DEFAULTPDBNAME129	"禁止领我玩"
#define DEFAULTPDBNAME130	"禁止新浪邮箱"
#define DEFAULTPDBNAME131	"禁止126邮箱"
#define DEFAULTPDBNAME132	"禁止163邮箱"
#define DEFAULTPDBNAME1		"禁止QQ"
#define DEFAULTPDBNAME134	"禁止猫扑"
#define DEFAULTPDBNAME135	"禁止天涯"
#define DEFAULTPDBNAME136	"禁止篱笆"
#define DEFAULTPDBNAME137	"禁止宽带山"
#define DEFAULTPDBNAME138	"禁止铁血"
#define DEFAULTPDBNAME139	"禁止凤凰"
#define DEFAULTPDBNAME140	"禁止西祠"
#define DEFAULTPDBNAME141	"禁止http代理"
#define DEFAULTPDBNAME142	"禁止SOCKS5代理"
#define DEFAULTPDBNAME143	"过滤文件类型"
#define DEFAULTPDBNAME144	"禁止网页提交输入"
#define DEFAULTPDBNAME145	"电信静态路由"
#define DEFAULTPDBNAME146	"联通静态路由"
#define DEFAULTPDBNAME147	"移动静态路由"
#define DEFAULTPDBNAME148	"禁止视频广告"

#if YAHOO_EN
#define DEFAULTPDBNAME149	"禁止雅虎通"
#define DEFAULTPDBNAME150	"禁止facebook"
#define DEFAULTPDBNAME151	"禁止youtube"
#define DEFAULTPDBNAME152	"禁止twitter"
#endif

#define DEFAULTPDBNAME153	"允许企业QQ"

#if (GAME_BOOST == FYES)
#define DEFAULTPDBNAME154	"加速英雄联盟"
#define DEFAULTPDBNAME155	"加速地下城与勇士"
#define DEFAULTPDBNAME156	"加速穿越火线"
#define DEFAULTPDBNAME157	"加速魔兽世界"
#define DEFAULTPDBNAME158	"加速梦幻西游"
#define DEFAULTPDBNAME159	"加速剑灵"
#define DEFAULTPDBNAME160	"加速Dota2"
#define DEFAULTPDBNAME161	"加速坦克世界"
#define DEFAULTPDBNAME162	"加速龙之谷"
#define DEFAULTPDBNAME163	"加速英雄三国"
#define DEFAULTPDBNAME164	"加速反恐精英OL"
#define DEFAULTPDBNAME165	"加速QQ炫舞"
#define DEFAULTPDBNAME166	"加速完美世界"
#define DEFAULTPDBNAME167	"加速炉石传说"
#define DEFAULTPDBNAME168	"加速QQ飞车"
#define DEFAULTPDBNAME169	"加速QQ语音"
#define DEFAULTPDBNAME170	"加速CCTV"
#define DEFAULTPDBNAME171	"加速新浪直播"
#define DEFAULTPDBNAME172	"加速QQ直播"
#endif
#define DEFAULTPDBNAME173   "禁止常用股票软件"
#if (WIFIDOG_AUTH == FYES)
/*微信策略更新*/
#define DEFAULTPDBNAME174	"放通微信策略"
#endif
#define DEFAULTPDBNAME175   "禁止微信"

#elif (CONFIG_USER_GOAHEAD_LANG_EN == FYES)

#define DEFAULTPDBNAME133	"Block QQ Mail"
#define DEFAULTPDBNAME2		"Block MSN"
#define DEFAULTPDBNAME3		"Block Ali Wangwang"	
#define DEFAULTPDBNAME4		"Block Web QQ"
#define DEFAULTPDBNAME5		"Block Fetion"
#define DEFAULTPDBNAME6		"Block BitComet,BitSpirit"
#define DEFAULTPDBNAME7		"Block Thunder Search"
#define DEFAULTPDBNAME8		"Block QQLive"
#define DEFAULTPDBNAME9		"Block PPS"
#define DEFAULTPDBNAME10	"Block KuGou Search"
#define DEFAULTPDBNAME11	"Block PPlive"
#define DEFAULTPDBNAME12	"Block QVOD"
#define DEFAULTPDBNAME13	"Block Baidu Player"
#define DEFAULTPDBNAME14	"Block Stock Sites"
#define DEFAULTPDBNAME15	"Block Youku.com"
#define DEFAULTPDBNAME16	"Block Tudou.com"
#define DEFAULTPDBNAME17	"Block iQIYI.com"
#define DEFAULTPDBNAME18	"Block Sohu.com"
#define DEFAULTPDBNAME19	"Block Thunder Kankan"
#define DEFAULTPDBNAME20	"Block Ku6"
#define DEFAULTPDBNAME21	"Block 56.com"
#define DEFAULTPDBNAME22	"Block Sina Video"
#define DEFAULTPDBNAME23	"Block QQLive"
#define DEFAULTPDBNAME24	"Block CNTV Video"
#define DEFAULTPDBNAME25	"Block Ifeng Video"
#define DEFAULTPDBNAME26	"Block Storm Codec"
#define DEFAULTPDBNAME27	"Block Joy.cn"
#define DEFAULTPDBNAME28	"Block PPS"
#define DEFAULTPDBNAME29	"Block Funshion"
#define DEFAULTPDBNAME30	"Block Game Sites"
#define DEFAULTPDBNAME31	"Block QQGame"
#define DEFAULTPDBNAME32	"Block BNB"
#define DEFAULTPDBNAME33	"Block Zhengtu"
#define DEFAULTPDBNAME34	"Block Perfect World,Jade Dynasty"
#define DEFAULTPDBNAME35	"Block MHXY"
#define DEFAULTPDBNAME36	"Block Audition"
#define DEFAULTPDBNAME37	"Block CGA"
#define DEFAULTPDBNAME38	"Block WOW"
#define DEFAULTPDBNAME39	"Block Aion"
#define DEFAULTPDBNAME40	"Block KartRider Rush"
#define DEFAULTPDBNAME41	"Block CrossFire"
#define DEFAULTPDBNAME46	"Block DragonNest"
#define DEFAULTPDBNAME47	"Block ShenXianZhuan"
#define DEFAULTPDBNAME48	"Block Legend"
#define DEFAULTPDBNAME49	"Block TLBB 3"
#define DEFAULTPDBNAME50	"Block CS Online"
#define DEFAULTPDBNAME52	"Block MapleStory"
#define DEFAULTPDBNAME53	"Block QNYH"
#define DEFAULTPDBNAME54	"Block AskTao"
#define DEFAULTPDBNAME55	"Block Meng3guo"
#define DEFAULTPDBNAME56	"Block World of Tanks"
#define DEFAULTPDBNAME57	"Block Taobao.com"
#define DEFAULTPDBNAME58	"Block Tmall.com"
#define DEFAULTPDBNAME59	"Block 360buy.com"
#define DEFAULTPDBNAME60	"Block Dangdang.com"
#define DEFAULTPDBNAME61	"Block Amazon.com"
#define DEFAULTPDBNAME62	"Block Paipai.com"
#define DEFAULTPDBNAME63	"Block Alibaba.com"
#define DEFAULTPDBNAME64	"Block M18.com"
#define DEFAULTPDBNAME65	"Block Hao123.com"
#define DEFAULTPDBNAME66	"Block Vancl.com"
#define DEFAULTPDBNAME67	"Block Vipshop"
#define DEFAULTPDBNAME68	"Block Fclub.com"
#define DEFAULTPDBNAME69	"Block Xiu.com"
#define DEFAULTPDBNAME70	"Block Shishangqiyi"
#define DEFAULTPDBNAME71	"Block Moonbasa"
#define DEFAULTPDBNAME72	"Block Yintai.com"
#define DEFAULTPDBNAME73	"Block Vjia.com"
#define DEFAULTPDBNAME74	"Block Masamasuo"
#define DEFAULTPDBNAME75	"Block Pb89.com"
#define DEFAULTPDBNAME76	"Block Suning.com"
#define DEFAULTPDBNAME77	"Block Gome.com"
#define DEFAULTPDBNAME78	"Block yixun.com"
#define DEFAULTPDBNAME79	"Block Coo8.com"
#define DEFAULTPDBNAME80	"Block Newegg.com"
#define DEFAULTPDBNAME81	"Block Lusen.com"
#define DEFAULTPDBNAME82	"Block OkBuy.com"
#define DEFAULTPDBNAME83	"Block Letao.com"
#define DEFAULTPDBNAME84	"Block Yougou.com"
#define DEFAULTPDBNAME85	"Block S.CN"
#define DEFAULTPDBNAME86	"Block Mbaobao.com"
#define DEFAULTPDBNAME87	"Block Lafaso.com"
#define DEFAULTPDBNAME88	"Block Tiantian.com"
#define DEFAULTPDBNAME89	"Block Sephora.com"
#define DEFAULTPDBNAME90	"Block DHC.net.cn"
#define DEFAULTPDBNAME91	"Block Jxdyf.com"
#define DEFAULTPDBNAME92	"Block StrawberryNet"
#define DEFAULTPDBNAME93	"Block Hitao.com"
#define DEFAULTPDBNAME94	"Block Guopi.com"
#define DEFAULTPDBNAME95	"Block Caomeipai"
#define DEFAULTPDBNAME96	"Block Redbaby"
#define DEFAULTPDBNAME97	"Block Muyingzhijia"
#define DEFAULTPDBNAME98	"Block Yihaodian.com"
#define DEFAULTPDBNAME99	"Block Womai.com"
#define DEFAULTPDBNAME100	"Block Lashou.com"
#define DEFAULTPDBNAME101	"Block Nuomi.com"
#define DEFAULTPDBNAME102	"Block Meituan.com"
#define DEFAULTPDBNAME103	"Block Gaopeng.com"
#define DEFAULTPDBNAME104	"Block 55tuan.com"
#define DEFAULTPDBNAME105	"Block Qzone"
#define DEFAULTPDBNAME106	"Block Renren.com"
#define DEFAULTPDBNAME107	"Block Pengyou.com"
#define DEFAULTPDBNAME108	"Block Sina Weibo"
#define DEFAULTPDBNAME109	"Block kaixin001"
#define DEFAULTPDBNAME110	"Block 51.com"
#define DEFAULTPDBNAME111	"Block Douban.com"
#define DEFAULTPDBNAME112	"Block 61.com"
#define DEFAULTPDBNAME113	"Block Temcent Weibo"
#define DEFAULTPDBNAME114	"Block Jiayuan.com"
#define DEFAULTPDBNAME115	"Block Tao Jianghu"
#define DEFAULTPDBNAME116	"Block Bai.sohu.com"
#define DEFAULTPDBNAME117	"Block Zhenai.com"
#define DEFAULTPDBNAME118	"Block Baihe.com"
#define DEFAULTPDBNAME119	"Block iPart.cn"
#define DEFAULTPDBNAME120	"Block Duowan.com"
#define DEFAULTPDBNAME121	"Block Baidu Games"
#define DEFAULTPDBNAME122	"Block 37wan.com"
#define DEFAULTPDBNAME123	"Block 256G.com"
#define DEFAULTPDBNAME124	"Block Eeyy.com"
#define DEFAULTPDBNAME125	"Block Kunlun.com"
#define DEFAULTPDBNAME126	"Block 4399.com"
#define DEFAULTPDBNAME127	"Block G.PPS.TV"
#define DEFAULTPDBNAME128	"Block Game7k7k.cn"
#define DEFAULTPDBNAME129	"Block 05wan.com"
#define DEFAULTPDBNAME130	"Block Sina Mail"
#define DEFAULTPDBNAME131	"Block 126 Mail"
#define DEFAULTPDBNAME132	"Block 163 Mail"
#define DEFAULTPDBNAME1		"Block QQ"
#define DEFAULTPDBNAME134	"Block MoP"
#define DEFAULTPDBNAME135	"Block Tianya"
#define DEFAULTPDBNAME136	"Block Liba"
#define DEFAULTPDBNAME137	"Block KDS"
#define DEFAULTPDBNAME138	"Block Tiexue"
#define DEFAULTPDBNAME139	"Block Ifeng"
#define DEFAULTPDBNAME140	"Block Xici"
#define DEFAULTPDBNAME141	"Block HTTP Proxy"
#define DEFAULTPDBNAME142	"Block SOCKS5 Proxy"
#define DEFAULTPDBNAME143	"Filter File"
#define DEFAULTPDBNAME144	"Block Web Submit"
#define DEFAULTPDBNAME145	"TEL Static Route"
#define DEFAULTPDBNAME146	"CNC Static Route"
#define DEFAULTPDBNAME147	"CMB Static Route"
#define DEFAULTPDBNAME148	"Block Advertisements and Videos"

#if YAHOO_EN 
#define DEFAULTPDBNAME149	"Block yahoo messenger"
#define DEFAULTPDBNAME150	"Block facebook"
#define DEFAULTPDBNAME151	"Block youtube"
#define DEFAULTPDBNAME152	"Block twitter"
#endif

#define DEFAULTPDBNAME153	"Block EnterpriseQQ"

#if (GAME_BOOST == FYES)
#define DEFAULTPDBNAME154	"加速英雄联盟"
#define DEFAULTPDBNAME155	"加速地下城与勇士"
#define DEFAULTPDBNAME156	"加速穿越火线"
#define DEFAULTPDBNAME157	"加速魔兽世界"
#define DEFAULTPDBNAME158	"加速梦幻西游"
#define DEFAULTPDBNAME159	"加速剑灵"
#define DEFAULTPDBNAME160	"加速Dota2"
#define DEFAULTPDBNAME161	"加速坦克世界"
#define DEFAULTPDBNAME162	"加速龙之谷"
#define DEFAULTPDBNAME163	"加速英雄三国"
#define DEFAULTPDBNAME164	"加速反恐精英OL"
#define DEFAULTPDBNAME165	"加速QQ炫舞"
#define DEFAULTPDBNAME166	"加速完美世界"
#define DEFAULTPDBNAME167	"加速炉石传说"
#define DEFAULTPDBNAME168	"加速QQ飞车"
#define DEFAULTPDBNAME169	"加速QQ语音"
#define DEFAULTPDBNAME170	"加速CCTV"
#define DEFAULTPDBNAME171	"加速新浪直播"
#define DEFAULTPDBNAME172	"加速QQ直播"
#endif
#define DEFAULTPDBNAME173   "en_禁止常用股票软件"
#if (WIFIDOG_AUTH == FYES)
/*微信策略更新*/
#define DEFAULTPDBNAME174	"en_放通微信策略"
#endif
#define DEFAULTPDBNAME175   "en_禁止微信"

#elif (CONFIG_USER_GOAHEAD_LANG_ZHTW == FYES)
#define DEFAULTPDBNAME133	"禁止QQ郵箱"
#define DEFAULTPDBNAME2		"禁止MSN"
#define DEFAULTPDBNAME3		"禁止阿裡旺旺登陸"	
#define DEFAULTPDBNAME4		"禁止網頁QQ"
#define DEFAULTPDBNAME5		"禁止飛信"
#define DEFAULTPDBNAME6		"禁止比特彗星、精靈"
#define DEFAULTPDBNAME7		"禁止迅雷搜索資源"
#define DEFAULTPDBNAME8		"禁止QQLive"
#define DEFAULTPDBNAME9		"禁止pps播放視頻"
#define DEFAULTPDBNAME10	"禁止酷狗搜索資源"
#define DEFAULTPDBNAME11	"禁止pplive播放視頻"
#define DEFAULTPDBNAME12	"禁止快播"
#define DEFAULTPDBNAME13	"禁止百度影音"
#define DEFAULTPDBNAME14	"禁止證券網站"
#define DEFAULTPDBNAME15	"禁止優酷網"
#define DEFAULTPDBNAME16	"禁止土豆網"
#define DEFAULTPDBNAME17	"禁止愛奇藝"
#define DEFAULTPDBNAME18	"禁止搜狐視頻"
#define DEFAULTPDBNAME19	"禁止迅雷看看"
#define DEFAULTPDBNAME20	"禁止酷6"
#define DEFAULTPDBNAME21	"禁止56網"
#define DEFAULTPDBNAME22	"禁止新浪視頻"
#define DEFAULTPDBNAME23	"禁止騰訊視頻"
#define DEFAULTPDBNAME24	"禁止CNTV視頻"
#define DEFAULTPDBNAME25	"禁止鳳凰視頻"
#define DEFAULTPDBNAME26	"禁止暴風影音"
#define DEFAULTPDBNAME27	"禁止激動網"
#define DEFAULTPDBNAME28	"禁止PPS"
#define DEFAULTPDBNAME29	"禁止風行"
#define DEFAULTPDBNAME30	"禁止遊戲網站"
#define DEFAULTPDBNAME31	"禁止QQGame"
#define DEFAULTPDBNAME32	"禁止泡泡堂遊戲"
#define DEFAULTPDBNAME33	"禁止征途"
#define DEFAULTPDBNAME34	"禁止完美世界，誅仙"
#define DEFAULTPDBNAME35	"禁止夢幻西遊遊戲"
#define DEFAULTPDBNAME36	"禁止勁舞團"
#define DEFAULTPDBNAME37	"禁止進入浩方"
#define DEFAULTPDBNAME38	"禁止魔獸世界"
#define DEFAULTPDBNAME39	"禁止永恆之塔"
#define DEFAULTPDBNAME40	"禁止跑跑卡丁車"
#define DEFAULTPDBNAME41	"禁止穿越火線"
#define DEFAULTPDBNAME46	"禁止龍之穀"
#define DEFAULTPDBNAME47	"禁止神仙傳"
#define DEFAULTPDBNAME48	"禁止傳奇"
#define DEFAULTPDBNAME49	"禁止天龍八部3"
#define DEFAULTPDBNAME50	"禁止反恐精英OL"
#define DEFAULTPDBNAME52	"禁止冒險島"
#define DEFAULTPDBNAME53	"禁止倩女幽魂"
#define DEFAULTPDBNAME54	"禁止問道"
#define DEFAULTPDBNAME55	"禁止夢三國"
#define DEFAULTPDBNAME56	"禁止坦克世界"
#define DEFAULTPDBNAME57	"禁止淘寶網"
#define DEFAULTPDBNAME58	"禁止淘寶商城"
#define DEFAULTPDBNAME59	"禁止京東商城"
#define DEFAULTPDBNAME60	"禁止當當網"
#define DEFAULTPDBNAME61	"禁止卓越網"
#define DEFAULTPDBNAME62	"禁止拍拍網"
#define DEFAULTPDBNAME63	"禁止阿裡巴巴"
#define DEFAULTPDBNAME64	"禁止麥考林"
#define DEFAULTPDBNAME65	"禁止hao123折扣"
#define DEFAULTPDBNAME66	"禁止凡客誠品"
#define DEFAULTPDBNAME67	"禁止唯品會"
#define DEFAULTPDBNAME68	"禁止聚尚網"
#define DEFAULTPDBNAME69	"禁止走秀網"
#define DEFAULTPDBNAME70	"禁止時尚起義"
#define DEFAULTPDBNAME71	"禁止夢芭莎購物"
#define DEFAULTPDBNAME72	"禁止銀泰網"
#define DEFAULTPDBNAME73	"禁止V+服飾"
#define DEFAULTPDBNAME74	"禁止瑪莎瑪索"
#define DEFAULTPDBNAME75	"禁止太平鳥"
#define DEFAULTPDBNAME76	"禁止蘇甯易購"
#define DEFAULTPDBNAME77	"禁止國美電器"
#define DEFAULTPDBNAME78	"禁止易迅網"
#define DEFAULTPDBNAME79	"禁止庫巴購物網"
#define DEFAULTPDBNAME80	"禁止新蛋網"
#define DEFAULTPDBNAME81	"禁止綠森數碼"
#define DEFAULTPDBNAME82	"禁止好樂買"
#define DEFAULTPDBNAME83	"禁止樂淘"
#define DEFAULTPDBNAME84	"禁止優購網"
#define DEFAULTPDBNAME85	"禁止名鞋庫"
#define DEFAULTPDBNAME86	"禁止麥包包"
#define DEFAULTPDBNAME87	"禁止樂蜂網"
#define DEFAULTPDBNAME88	"禁止天天網"
#define DEFAULTPDBNAME89	"禁止絲芙網"
#define DEFAULTPDBNAME90	"禁止DHC化妝品"
#define DEFAULTPDBNAME91	"禁止金象大藥房"
#define DEFAULTPDBNAME92	"禁止草莓網"
#define DEFAULTPDBNAME93	"禁止嗨淘網"
#define DEFAULTPDBNAME94	"禁止果皮網"
#define DEFAULTPDBNAME95	"禁止草莓派"
#define DEFAULTPDBNAME96	"禁止紅孩子"
#define DEFAULTPDBNAME97	"禁止母嬰之家"
#define DEFAULTPDBNAME98	"禁止一號店"
#define DEFAULTPDBNAME99	"禁止我買網"
#define DEFAULTPDBNAME100	"禁止拉手網"
#define DEFAULTPDBNAME101	"禁止糯米網"
#define DEFAULTPDBNAME102	"禁止美團網"
#define DEFAULTPDBNAME103	"禁止高朋網"
#define DEFAULTPDBNAME104	"禁止窩窩團"
#define DEFAULTPDBNAME105	"禁止QQ空間"
#define DEFAULTPDBNAME106	"禁止人人網"
#define DEFAULTPDBNAME107	"禁止朋友網"
#define DEFAULTPDBNAME108	"禁止新浪微博"
#define DEFAULTPDBNAME109	"禁止kaixin001"
#define DEFAULTPDBNAME110	"禁止51.com"
#define DEFAULTPDBNAME111	"禁止豆瓣"
#define DEFAULTPDBNAME112	"禁止淘米"
#define DEFAULTPDBNAME113	"禁止騰訊微博"
#define DEFAULTPDBNAME114	"禁止佳緣網"
#define DEFAULTPDBNAME115	"禁止淘江湖"
#define DEFAULTPDBNAME116	"禁止白社會"
#define DEFAULTPDBNAME117	"禁止珍愛網"
#define DEFAULTPDBNAME118	"禁止百合網"
#define DEFAULTPDBNAME119	"禁止愛情公寓"
#define DEFAULTPDBNAME120	"禁止多玩"
#define DEFAULTPDBNAME121	"禁止百度遊戲"
#define DEFAULTPDBNAME122	"禁止37玩"
#define DEFAULTPDBNAME123	"禁止256G"
#define DEFAULTPDBNAME124	"禁止一遊"
#define DEFAULTPDBNAME125	"禁止昆侖線上"
#define DEFAULTPDBNAME126	"禁止4399小遊戲"
#define DEFAULTPDBNAME127	"禁止pps遊戲平臺"
#define DEFAULTPDBNAME128	"禁止7k7k小遊戲"
#define DEFAULTPDBNAME129	"禁止領我玩"
#define DEFAULTPDBNAME130	"禁止新浪郵箱"
#define DEFAULTPDBNAME131	"禁止126郵箱"
#define DEFAULTPDBNAME132	"禁止163郵箱"
#define DEFAULTPDBNAME1		"禁止QQ"
#define DEFAULTPDBNAME134	"禁止貓撲"
#define DEFAULTPDBNAME135	"禁止天涯"
#define DEFAULTPDBNAME136	"禁止籬笆"
#define DEFAULTPDBNAME137	"禁止寬頻山"
#define DEFAULTPDBNAME138	"禁止鐵血"
#define DEFAULTPDBNAME139	"禁止鳳凰"
#define DEFAULTPDBNAME140	"禁止西祠"
#define DEFAULTPDBNAME141	"禁止http代理"
#define DEFAULTPDBNAME142	"禁止SOCKS5代理"
#define DEFAULTPDBNAME143	"過濾檔案類型"
#define DEFAULTPDBNAME144	"禁止網頁提交輸入"
#define DEFAULTPDBNAME145	"電信靜態路由"
#define DEFAULTPDBNAME146	"聯通靜態路由"
#define DEFAULTPDBNAME147	"移動靜態路由"
#define DEFAULTPDBNAME148	"禁止视频广告"


#if YAHOO_EN
#define DEFAULTPDBNAME149	"雅虎通"
#define DEFAULTPDBNAME150	"禁止facebook"
#define DEFAULTPDBNAME151	"禁止youtube"
#define DEFAULTPDBNAME152	"禁止twitter"
#endif

#define DEFAULTPDBNAME153	"允许企业QQ"

#if (GAME_BOOST == FYES)
#define DEFAULTPDBNAME154	"加速英雄聯盟"
#define DEFAULTPDBNAME155	"加速地下城与勇士"
#define DEFAULTPDBNAME156	"加速穿越火线"
#define DEFAULTPDBNAME157	"加速魔兽世界"
#define DEFAULTPDBNAME158	"加速梦幻西游"
#define DEFAULTPDBNAME159	"加速剑灵"
#define DEFAULTPDBNAME160	"加速Dota2"
#define DEFAULTPDBNAME161	"加速坦克世界"
#define DEFAULTPDBNAME162	"加速龙之谷"
#define DEFAULTPDBNAME163	"加速英雄三国"
#define DEFAULTPDBNAME164	"加速反恐精英OL"
#define DEFAULTPDBNAME165	"加速QQ炫舞"
#define DEFAULTPDBNAME166	"加速完美世界"
#define DEFAULTPDBNAME167	"加速炉石传说"
#define DEFAULTPDBNAME168	"加速QQ飞车"
#define DEFAULTPDBNAME169	"加速QQ语音"
#define DEFAULTPDBNAME170	"加速CCTV"
#define DEFAULTPDBNAME171	"加速新浪直播"
#define DEFAULTPDBNAME172	"加速QQ直播"
#endif
#define DEFAULTPDBNAME173   "tw_禁止常用股票软件"
#if (WIFIDOG_AUTH == FYES)
/*微信策略更新*/
#define DEFAULTPDBNAME174	"tw_放通微信策略"
#endif
#define DEFAULTPDBNAME175   "tw_禁止微信"
#endif
#endif
