#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "/opt/buildroot-gcc342/bin/mipsel-linux-uclibc-gcc  -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS  -Os -DL_ENDIAN -mips2 -mno-branch-likely -G 0 -fno-builtin -DCPU=MIPS32 -DMIPSEL -DNO_STRINGS_H"
  #define PLATFORM "RT2880"
  #define DATE "Tue Apr 14 13:14:02 CST 2009"
#endif
