#!/bin/sh
mount -a
#internet.sh
mkdir -p /var/run
mkdir -p /tmp/urcp/images
mkdir -p /tmp/urcp/ap_configs
initdev.sh
cat /etc_ro/motd
touch /etc/utt-speedmsg
touch /etc/utt-nvramshm
touch /tmp/uttMsgforRoute
touch /tmp/uttshmfornvram
touch /tmp/uttPppoeSrvMsg
touch /tmp/uttSemForSpeedweb
touch /tmp/uttMsgforCwmp
speedweb&
nvram_daemon&
date -s 010100002011
sleep 3
#goahead&
#easyNetbios&
urcp&

#for telnet debugging
telnetd

#for crond
cron-init.sh

#for syslogd
mkdir -p /var/log
