    /*
     * Notice: file generated by MIBMAKE from mibbridg.mdf
     * DO NOT EDIT THIS FILE!!!  Edit mibbridg.mdf
     */
#line 2 "mibbridg.mdf"
/*
 * $Id: mibbridg.h,v 1.1.1.1 2011/08/17 11:11:56 brwang Exp $
 *
 *      Copyright (c) 1995 UTT Technologies, Inc.
 *      All rights reserved.
 *      Use of copyright notice does not imply publication.
 *
 *
 *                      CONFIDENTIAL INFORMATION
 *                      ------------------------
 *      This Document contains Confidential Information or Trade Secrets,
 *      or both, which are the property of UTT Technologies, Inc.
 *      This document may not be copied, reproduced, reduced to any
 *      electronic medium or machine readable form or otherwise duplicated
 *      and the information herein may not be used, disseminated or
 *      otherwise disclosed, except with the prior written consent of
 *      UTT Technologies, Inc.
 */

#line 24 "mibbridg.mdf"

#if ! defined( MIBBRIDG_H )
#define MIBBRIDG_H

    /* This file contains the internal representation of the bridge profile
     * (MIB_PROF_BRIDGE). The name of this profile is stored in the global
     * variable mibProfBridge.
     */

extern const char* const		mibProfBridge;


    /*
     * BridgeProfile:
     *
     * To do bridging we need to know the ethernet numbers that we are going to
     * dial calls for. The BridgeProfile provides this information.
     *
     *  etherAddress The ethernet address of this entry.
     *
     *  netAddress The network layer address, if any, of this address. We will
     *                                  ARP requests for this address.
     *
     *  profileNumber The number of the internet profile used to place calls to
     *                                  this address. All of the connection
     *                                  parameters come from the numbered
     *                                  profile.
     */
typedef struct bridgeProfile {
#line 61 "mibbridg.mdf"
    char                                name[MAX_PROFILE_NAME_LENGTH+1];
    Boolean                             active;
    EtherAddress                        etherAddress;
#line 65 "mibbridg.mdf"
#if ( MDF_IP == FYES )
    IpAddress                           netAddress;
#endif /* ( MDF_IP == FYES ) */
#line 71 "mibbridg.mdf"
    Word                                profileNumber;
}
#if ( USERIF & CLI )
__PACK__
#endif
BridgeProfile;
#line 100 "mibbridg.mdf"

#endif /* MIBBRIDG_H */

