    /*
     * Notice: file generated by MIBMAKE from mibinx75.mdf
     * DO NOT EDIT THIS FILE!!!  Edit mibinx75.mdf
     */
#line 3 "mibinx75.mdf"
/*
 * $Id: mibinx75.h,v 1.1.1.1 2011/08/17 11:11:56 brwang Exp $
 *
 *      Copyright (c) 1996 UTT Technologies, Inc.
 *      All rights reserved.
 *      Use of copyright notice does not imply publication.
 *
 *
 *                      CONFIDENTIAL INFORMATION
 *                      ------------------------
 *      This Document contains Confidential Information or Trade Secrets,
 *      or both, which are the property of UTT Technologies, Inc.
 *      This document may not be copied, reproduced, reduced to any
 *      electronic medium or machine readable form or otherwise duplicated
 *      and the information herein may not be used, disseminated or
 *      otherwise disclosed, except with the prior written consent of
 *      UTT Technologies, Inc.
 */

#line 32 "mibinx75.mdf"

#if (( ! defined( MIBINX75_H ) ) && ( MDF_X75 == FYES ))
#define MIBINX75_H

#include "mibgen.h"
#include "mibglob.h"

    /*
     * How to build the factory instance of this profile.
     */
extern ConstPtr
mibFactoryX75Options( MibProfileType	mibType,
		       Uint32		info );

    /*
     * Our parameter table is made external as the profile is used
     * within other profiles.
     */
extern const MibFieldComplexParams	x75OptionsParams;


    /*
     * X75Options:
     *
     * A structure containing variable parameters used by the X.75 system. Few
     * of these are user changeable at this time, but that may change in the
     * future.
     *
     *  x75Enabled Hidden, for answer profile.
     *
     *  kFramesOutstanding Number of frames outstanding before we require an
     *                                  ack. Defaults to 7.
     *
     *  n2Retransmissions Number of retransmissions allowed. Defaults to 10.
     *
     *  t1RetranTimer Number of milliseconds between retransmissions. Defaults
     *                                  to 1000.
     *
     *  infoLen Frame length to use for incoming X.75 connections. Defaults to
     *                                  1024.
     */
typedef struct x75Options {
#line 105 "mibinx75.mdf"
    Bool                                x75Enabled;
#line 111 "mibinx75.mdf"
    Uint16                              kFramesOutstanding;
#line 115 "mibinx75.mdf"
    Uint16                              n2Retransmissions;
#line 119 "mibinx75.mdf"
    Uint16                              t1RetranTimer;
#line 123 "mibinx75.mdf"
    Uint16                              infoLen;
}
#if ( USERIF & CLI )
__PACK__
#endif
X75Options;
#line 192 "mibinx75.mdf"

#endif /* (( ! defined( MIBINX75_H ) ) && ( MDF_X75 == FYES )) */

