    /*
     * Notice: file generated by MIBMAKE from mibincomb.mdf
     * DO NOT EDIT THIS FILE!!!  Edit mibincomb.mdf
     */
#line 3 "mibincomb.mdf"
/*
 * $Id: mibincomb.h,v 1.1.1.1 2011/08/17 11:11:56 brwang Exp $
 *
 *      Copyright (c) 1996 UTT Technologies, Inc.
 *      All rights reserved.
 *      Use of copyright notice does not imply publication.
 *
 *
 *                      CONFIDENTIAL INFORMATION
 *                      ------------------------
 *      This Document contains Confidential Information or Trade Secrets,
 *      or both, which are the property of UTT Technologies, Inc.
 *      This document may not be copied, reproduced, reduced to any
 *      electronic medium or machine readable form or otherwise duplicated
 *      and the information herein may not be used, disseminated or
 *      otherwise disclosed, except with the prior written consent of
 *      UTT Technologies, Inc.
 */

#line 33 "mibincomb.mdf"

#if (( ! defined( MIBINCOMB_H ) ) && ( MDF_COMB == FYES ))
#define MIBINCOMB_H

#include "mibgen.h"
#include "mibglob.h"
#include "mibcomp.h"

    /*
     * How to build the factory instance of this profile.
     */
extern ConstPtr
mibFactoryCombOptions( MibProfileType	mibType,
		       Uint32		info );

    /*
     * Our parameter table is made external as the profile is used
     * within other profiles.
     */
extern const MibFieldComplexParams	combOptionsParams;


    /*
     * CombOptions:
     *
     * Combinet configuration options.
     *
     *  combEnabled Hidden, for answer profile
     *
     *  combPwReqd Should a password be sent to the far end when placing a
     *                                  combinet style call.
     *
     *  sendPassword The password to send to the far end. For future use. We
     *                                  currently use the password in the PPP
     *                                  sub-profile.
     *
     *  recvPassword The password to send to the far end. For future use. We
     *                                  currently use the password in the PPP
     *                                  sub-profile.
     *
     *  fill1
     *
     *  interval The combinet link integrety interval.
     *
     *  baseChannelCount The number of channels that should be dialed.
     *
     *  compressionType Should compression be used.
     */
typedef struct combOptions {
#line 92 "mibincomb.mdf"
    Boolean                             combEnabled;
#line 98 "mibincomb.mdf"
    Boolean                             combPwReqd;
#line 104 "mibincomb.mdf"
#if ( PLATFORM & TNT )
    char                                sendPassword[ MAX_PASSWORD_LENGTH + 1 ];
#endif /* ( PLATFORM & TNT ) */
#line 112 "mibincomb.mdf"
#if ( PLATFORM & TNT )
    char                                recvPassword[ MAX_PASSWORD_LENGTH + 1 ];
#endif /* ( PLATFORM & TNT ) */
#line 120 "mibincomb.mdf"
#if ( ! ( PLATFORM & TNT ))
    Uint16                              fill1;
#endif /* ( ! ( PLATFORM & TNT )) */
#line 126 "mibincomb.mdf"
    Uint16                              interval;
#line 131 "mibincomb.mdf"
    Uint16                              baseChannelCount;
#line 136 "mibincomb.mdf"
#if ( PLATFORM & TNT )
    CompressionType                     compressionType;
#endif /* ( PLATFORM & TNT ) */
}
#if ( USERIF & CLI )
__PACK__
#endif
CombOptions;
#line 197 "mibincomb.mdf"

#endif /* (( ! defined( MIBINCOMB_H ) ) && ( MDF_COMB == FYES )) */

