    /*
     * Notice: file generated by MIBMAKE from mibplan.mdf
     * DO NOT EDIT THIS FILE!!!  Edit mibplan.mdf
     */
#line 2 "mibplan.mdf"
/*
 * $Id: mibplan.h,v 1.1.1.1 2011/08/17 11:11:56 brwang Exp $
 *
 *      Copyright (c) 1995 UTT Technologies, Inc.
 *      All rights reserved.
 *      Use of copyright notice does not imply publication.
 *
 *
 *                      CONFIDENTIAL INFORMATION
 *                      ------------------------
 *      This Document contains Confidential Information or Trade Secrets,
 *      or both, which are the property of UTT Technologies, Inc.
 *      This document may not be copied, reproduced, reduced to any
 *      electronic medium or machine readable form or otherwise duplicated
 *      and the information herein may not be used, disseminated or
 *      otherwise disclosed, except with the prior written consent of
 *      UTT Technologies, Inc.
 */

#line 24 "mibplan.mdf"

#if ! defined( MIBPLAN_H )
#define MIBPLAN_H

#include "mibsct.h"


    /* This file contains the internal representation of the plan profile
     * (MIB_PROF_PLAN). The name of this profile is stored in the global
     * variable mibProfPlan.
     */

extern const char* const		mibProfPlan;


    /*
     * PlanProfile:
     *
     * The dial plan profile defines call setup information used when the
     * extended dial plan option is enabled.
     *
     *  name
     *
     *  callByCallID
     *
     *  switchedCallType
     *
     *  calledNumberType PRI Called Party element's Type-Of-Number value for
     *                                  outgoing T1-to-PRI calls. MUST be a
     *                                  native int.
     *
     *  transitNumber
     *
     *  billingNumber
     *
     *  prependDigits
     *
     *  priNumberingPlanID PRI Called Party element's Numbering-Plan-ID value
     *                                  for outgoing T1-to-PRI calls.
     *
     *  destNumber Phone number to use for outgoing call. Replaces incoming
     *                                  number.
     */
typedef struct planProfile {
#line 62 "mibplan.mdf"
    Byte                                name[ MAX_NAME_LEN + 1 ];
#line 65 "mibplan.mdf"
    Word                                callByCallID;
#line 68 "mibplan.mdf"
    SwitchedCallType                    switchedCallType;
#line 71 "mibplan.mdf"
    int                                 calledNumberType;
#line 77 "mibplan.mdf"
    char                                transitNumber[ MAX_TRANSIT_NUMBER_LENGTH + 1 ];
#line 80 "mibplan.mdf"
    char                                billingNumber[ MAX_BILLING_NUMBER_LENGTH + 1 ];
#line 83 "mibplan.mdf"
    char                                prependDigits[ MAX_PHONE_NUMBER_LENGTH + 1 ];
#line 86 "mibplan.mdf"
#if ( ( PLATFORM & MPORT ) && ( NETIF & T1 ) )
    int                                 priNumberingPlanID;
#endif /* ( ( PLATFORM & MPORT ) && ( NETIF & T1 ) ) */
#line 92 "mibplan.mdf"
#if ( MAXDAX == FYES )
    char                                destNumber[ MAX_PHONE_NUMBER_LENGTH + 1 ];
#endif /* ( MAXDAX == FYES ) */
}
#if ( USERIF & CLI )
__PACK__
#endif
PlanProfile;
#line 119 "mibplan.mdf"

#endif /* MIBPLAN_H */

