    /*
     * Notice: file generated by MIBMAKE from mibtsecm.mdf
     * DO NOT EDIT THIS FILE!!!  Edit mibtsecm.mdf
     */
#line 3 "mibtsecm.mdf"
/*
 * $Id: mibtsecm.h,v 1.1.1.1 2011/08/17 11:11:56 brwang Exp $
 *
 *      Copyright (c) 1996 UTT Technologies, Inc.
 *      All rights reserved.
 *      Use of copyright notice does not imply publication.
 *
 *
 *                      CONFIDENTIAL INFORMATION
 *                      ------------------------
 *      This Document contains Confidential Information or Trade Secrets,
 *      or both, which are the property of UTT Technologies, Inc.
 *      This document may not be copied, reproduced, reduced to any
 *      electronic medium or machine readable form or otherwise duplicated
 *      and the information herein may not be used, disseminated or
 *      otherwise disclosed, except with the prior written consent of
 *      UTT Technologies, Inc.
 */

    /*
     * Define the enumerated type TsErrorCorrectionMode and it's CLI lookup
     * tables.
     */
#line 29 "mibtsecm.mdf"

#if ! defined( MIBTSECM_H )
#define MIBTSECM_H

#include "mibgen.h"

#if ( USERIF & CLI )

extern const MibFieldEnumParams	tsErrorCorrectionModeParams;

#endif /* ( USERIF & CLI ) */


    /*
     * TsErrorCorrectionMode:
     *
     * Determine how our modems should negotiate LAPM/MNP Error control.
     *
     *  TS_V42_WONT Don't use LAPM/MNP at all.
     *
     *  TS_V42_WILL Request LAPM/MNP, but accept call if none.
     *
     *  TS_V42_MUST Request LAPM/MNP, drop call if none.
     */
typedef enum TsErrorCorrectionMode {
#line 56 "mibtsecm.mdf"
    TS_V42_WONT,
#line 59 "mibtsecm.mdf"
    TS_V42_WILL,
#line 62 "mibtsecm.mdf"
    TS_V42_MUST
} TsErrorCorrectionMode;


static __inline__ Bool
validTsErrorCorrectionMode (int x)
{
    switch (x) {
#line 56 "mibtsecm.mdf"
    case TS_V42_WONT:
#line 59 "mibtsecm.mdf"
    case TS_V42_WILL:
#line 62 "mibtsecm.mdf"
    case TS_V42_MUST:
        return TRUE;
    default:
        return FALSE;
    }
}
#line 82 "mibtsecm.mdf"

#endif /* MIBTSECM_H */

