    /*
     * Notice: file generated by MIBMAKE from mibtsis.mdf
     * DO NOT EDIT THIS FILE!!!  Edit mibtsis.mdf
     */
#line 3 "mibtsis.mdf"
/*
 * $Id: mibtsis.h,v 1.1.1.1 2011/08/17 11:11:56 brwang Exp $
 *
 *      Copyright (c) 1996 UTT Technologies, Inc.
 *      All rights reserved.
 *      Use of copyright notice does not imply publication.
 *
 *
 *                      CONFIDENTIAL INFORMATION
 *                      ------------------------
 *      This Document contains Confidential Information or Trade Secrets,
 *      or both, which are the property of UTT Technologies, Inc.
 *      This document may not be copied, reproduced, reduced to any
 *      electronic medium or machine readable form or otherwise duplicated
 *      and the information herein may not be used, disseminated or
 *      otherwise disclosed, except with the prior written consent of
 *      UTT Technologies, Inc.
 */

    /*
     * Define the enumerated type ImmediateServiceType and it's CLI lookup
     * tables.
     */
#line 29 "mibtsis.mdf"

#if ! defined( MIBTSIS_H )
#define MIBTSIS_H

#include "mibgen.h"

#if ( USERIF & CLI )

extern const MibFieldEnumParams immediateServiceTypeParams;

#endif /* ( USERIF & CLI ) */


    /*
     * ImmediateServiceType:
     *
     * Immediate Service Type Enumeration
     *
     *  IMMEDIATE_NONE No Immediate service.
     *
     *  IMMEDIATE_TELNET Immediate Telnet.
     *
     *  IMMEDIATE_RAWTCP Immediate Raw Tcp.
     *
     *  IMMEDIATE_RLOGIN Immediate Rlogin.
     *
     *  IMMEDIATE_X25PAD Immediate X25/PAD.
     *
     *  IMMEDIATE_T3POS Immediate X25/T3POS.
     */
typedef enum ImmediateServiceType {
#line 56 "mibtsis.mdf"
    IMMEDIATE_NONE,
#line 59 "mibtsis.mdf"
    IMMEDIATE_TELNET,
#line 62 "mibtsis.mdf"
    IMMEDIATE_RAWTCP,
#line 65 "mibtsis.mdf"
    IMMEDIATE_RLOGIN,
#line 68 "mibtsis.mdf"
    IMMEDIATE_X25PAD,
#line 71 "mibtsis.mdf"
    IMMEDIATE_T3POS
} ImmediateServiceType;


static __inline__ Bool
validImmediateServiceType (int x)
{
    switch (x) {
#line 56 "mibtsis.mdf"
    case IMMEDIATE_NONE:
#line 59 "mibtsis.mdf"
    case IMMEDIATE_TELNET:
#line 62 "mibtsis.mdf"
    case IMMEDIATE_RAWTCP:
#line 65 "mibtsis.mdf"
    case IMMEDIATE_RLOGIN:
#line 68 "mibtsis.mdf"
    case IMMEDIATE_X25PAD:
#line 71 "mibtsis.mdf"
    case IMMEDIATE_T3POS:
        return TRUE;
    default:
        return FALSE;
    }
}
#line 91 "mibtsis.mdf"

#endif /* MIBTSIS_H */

