    /*
     * Notice: file generated by MIBMAKE from mibtsmbr.mdf
     * DO NOT EDIT THIS FILE!!!  Edit mibtsmbr.mdf
     */
#line 3 "mibtsmbr.mdf"
/*
 * $Id: mibtsmbr.h,v 1.1.1.1 2011/08/17 11:11:56 brwang Exp $
 *
 *      Copyright (c) 1996 UTT Technologies, Inc.
 *      All rights reserved.
 *      Use of copyright notice does not imply publication.
 *
 *
 *                      CONFIDENTIAL INFORMATION
 *                      ------------------------
 *      This Document contains Confidential Information or Trade Secrets,
 *      or both, which are the property of UTT Technologies, Inc.
 *      This document may not be copied, reproduced, reduced to any
 *      electronic medium or machine readable form or otherwise duplicated
 *      and the information herein may not be used, disseminated or
 *      otherwise disclosed, except with the prior written consent of
 *      UTT Technologies, Inc.
 */

    /*
     * Define the enumerated type TsErrorCorrectionMode and it's CLI lookup
     * tables.
     */
#line 29 "mibtsmbr.mdf"

#if ! defined( MIBTSMBR_H )
#define MIBTSMBR_H

#include "mibgen.h"

#if ( USERIF & CLI )

extern const MibFieldEnumParams	tsMaxBaudRateParams;

#endif /* ( USERIF & CLI ) */


    /*
     * TsMaxBaudRate:
     *
     * Determine the maximum baud rate the V.34 modems should try.
     *
     *  TS_MAX_BAUD_33600 max baud rate 33600
     *
     *  TS_MAX_BAUD_31200 max baud rate 31200
     *
     *  TS_MAX_BAUD_28800 max baud rate 28800
     *
     *  TS_MAX_BAUD_26400 max baud rate 26400
     *
     *  TS_MAX_BAUD_24000 max baud rate 24000
     *
     *  TS_MAX_BAUD_21600 max baud rate 21600
     *
     *  TS_MAX_BAUD_19200 max baud rate 19200
     *
     *  TS_MAX_BAUD_16800 max baud rate 16800
     *
     *  TS_MAX_BAUD_14400 max baud rate 14400
     *
     *  TS_MAX_BAUD_12000 max baud rate 12000
     *
     *  TS_MAX_BAUD_09600 max baud rate 09600
     *
     *  TS_MAX_BAUD_07200 max baud rate 07200
     *
     *  TS_MAX_BAUD_04800 max baud rate 04800
     *
     *  TS_MAX_BAUD_02400 max baud rate 02400
     */
typedef enum TsMaxBaudRate {
#line 56 "mibtsmbr.mdf"
    TS_MAX_BAUD_33600,
#line 59 "mibtsmbr.mdf"
    TS_MAX_BAUD_31200,
#line 62 "mibtsmbr.mdf"
    TS_MAX_BAUD_28800,
#line 65 "mibtsmbr.mdf"
    TS_MAX_BAUD_26400,
#line 68 "mibtsmbr.mdf"
    TS_MAX_BAUD_24000,
#line 71 "mibtsmbr.mdf"
    TS_MAX_BAUD_21600,
#line 74 "mibtsmbr.mdf"
    TS_MAX_BAUD_19200,
#line 77 "mibtsmbr.mdf"
    TS_MAX_BAUD_16800,
#line 80 "mibtsmbr.mdf"
    TS_MAX_BAUD_14400,
#line 83 "mibtsmbr.mdf"
    TS_MAX_BAUD_12000,
#line 86 "mibtsmbr.mdf"
    TS_MAX_BAUD_09600,
#line 89 "mibtsmbr.mdf"
    TS_MAX_BAUD_07200,
#line 92 "mibtsmbr.mdf"
    TS_MAX_BAUD_04800,
#line 95 "mibtsmbr.mdf"
    TS_MAX_BAUD_02400
} TsMaxBaudRate;


static __inline__ Bool
validTsMaxBaudRate (int x)
{
    switch (x) {
#line 56 "mibtsmbr.mdf"
    case TS_MAX_BAUD_33600:
#line 59 "mibtsmbr.mdf"
    case TS_MAX_BAUD_31200:
#line 62 "mibtsmbr.mdf"
    case TS_MAX_BAUD_28800:
#line 65 "mibtsmbr.mdf"
    case TS_MAX_BAUD_26400:
#line 68 "mibtsmbr.mdf"
    case TS_MAX_BAUD_24000:
#line 71 "mibtsmbr.mdf"
    case TS_MAX_BAUD_21600:
#line 74 "mibtsmbr.mdf"
    case TS_MAX_BAUD_19200:
#line 77 "mibtsmbr.mdf"
    case TS_MAX_BAUD_16800:
#line 80 "mibtsmbr.mdf"
    case TS_MAX_BAUD_14400:
#line 83 "mibtsmbr.mdf"
    case TS_MAX_BAUD_12000:
#line 86 "mibtsmbr.mdf"
    case TS_MAX_BAUD_09600:
#line 89 "mibtsmbr.mdf"
    case TS_MAX_BAUD_07200:
#line 92 "mibtsmbr.mdf"
    case TS_MAX_BAUD_04800:
#line 95 "mibtsmbr.mdf"
    case TS_MAX_BAUD_02400:
        return TRUE;
    default:
        return FALSE;
    }
}
#line 115 "mibtsmbr.mdf"

#endif /* MIBTSMBR_H */

