# gmp-5.0.4 在编译软件的时候调用./configure 生成Makefile
#
#
#

ABI=
CFLAGS=
LDFLAGS=
LIBS=
CPPFLAGS=
CPP=
CC_FOR_BUILD=
CPP_FOR_BUILD=
CXX=
CXXFLAGS=
CXXCPP=
M4=
YACC=
YFLAGS=

all:
	@if [ ! -f Makefile ]; then \
	./configure --host=$(ARCH) CC=$(CC); \
	fi;
	make
	install -d ../lib
	install -m 644  ./.libs/libgmp.a ../lib
