    /*
     * Notice: file generated by MIBMAKE from mibdest.mdf
     * DO NOT EDIT THIS FILE!!!  Edit mibdest.mdf
     */
#line 2 "mibdest.mdf"
/*
 * $Id: mibdest.h,v 1.1.1.1 2011/08/17 11:11:56 brwang Exp $
 *
 *      Copyright (c) 1995 UTT Technologies, Inc.
 *      All rights reserved.
 *      Use of copyright notice does not imply publication.
 *
 *
 *                      CONFIDENTIAL INFORMATION
 *                      ------------------------
 *      This Document contains Confidential Information or Trade Secrets,
 *      or both, which are the property of UTT Technologies, Inc.
 *      This document may not be copied, reproduced, reduced to any
 *      electronic medium or machine readable form or otherwise duplicated
 *      and the information herein may not be used, disseminated or
 *      otherwise disclosed, except with the prior written consent of
 *      UTT Technologies, Inc.
 */

#line 24 "mibdest.mdf"

#if ! defined( MIBDEST_H )
#define MIBDEST_H

    /* This file contains the internal representation of the dest profile
     * (MIB_PROF_DEST). The name of this profile is stored in the global
     * variable mibProfDest.
     */

extern const char* const		mibProfDest;

    /*
     * The maximum number of destination numbers per destination
     * profile.
     */
#define MAX_DEST_NUMBERS 	6


    /*
     * DestSelectOpt:
     *
     * This enumeration defines the possible trunk group selection criteria.
     *
     *  DEST_SEL_FIRST_AVAIL
     *
     *  DEST_SEL_FIRST_ACTIVE
     *
     *  DEST_SEL_ANY_AVAIL
     *
     *  NUMBER_OF_DEST_SEL
     */
typedef enum DestSelectOpt {
#line 64 "mibdest.mdf"
    DEST_SEL_FIRST_AVAIL,
#line 65 "mibdest.mdf"
    DEST_SEL_FIRST_ACTIVE,
#line 66 "mibdest.mdf"
    DEST_SEL_ANY_AVAIL,
#line 67 "mibdest.mdf"
    NUMBER_OF_DEST_SEL
} DestSelectOpt;


static __inline__ Bool
validDestSelectOpt (int x)
{
    switch (x) {
#line 64 "mibdest.mdf"
    case DEST_SEL_FIRST_AVAIL:
#line 65 "mibdest.mdf"
    case DEST_SEL_FIRST_ACTIVE:
#line 66 "mibdest.mdf"
    case DEST_SEL_ANY_AVAIL:
#line 67 "mibdest.mdf"
    case NUMBER_OF_DEST_SEL:
        return TRUE;
    default:
        return FALSE;
    }
}

    /*
     * DestNumber:
     *
     * Destination numbers are coupled with their callByCallID for use when PRI
     * signaling is selected.
     *
     *  phoneNumber
     *
     *  callByCallID
     */
typedef struct destNumber {
#line 92 "mibdest.mdf"
    char                                phoneNumber[ MAX_PHONE_NUMBER_LENGTH + 1 ];
#line 95 "mibdest.mdf"
    Word                                callByCallID;
}
#if ( USERIF & CLI )
__PACK__
#endif
DestNumber;

    /*
     * DestProfile:
     *
     * The destination profile defines up to six possible destination numbers
     * for a trunk group which can be dialed based on the destination selection
     * option.
     *
     *  name
     *
     *  numberOption
     *
     *  destNumber
     */
typedef struct destProfile {
#line 137 "mibdest.mdf"
    Byte                                name[ MAX_NAME_LEN + 1 ];
#line 140 "mibdest.mdf"
    DestSelectOpt                       numberOption;
#line 143 "mibdest.mdf"
    DestNumber                          destNumber[ MAX_DEST_NUMBERS ];
}
#if ( USERIF & CLI )
__PACK__
#endif
DestProfile;
#line 169 "mibdest.mdf"

#endif /* MIBDEST_H */

