    /*
     * Notice: file generated by MIBMAKE from mibinfr.mdf
     * DO NOT EDIT THIS FILE!!!  Edit mibinfr.mdf
     */
#line 3 "mibinfr.mdf"
/*
 * $Id: mibinfr.h,v 1.1.1.1 2011/08/17 11:11:56 brwang Exp $
 *
 *      Copyright (c) 1996 UTT Technologies, Inc.
 *      All rights reserved.
 *      Use of copyright notice does not imply publication.
 *
 *
 *                      CONFIDENTIAL INFORMATION
 *                      ------------------------
 *      This Document contains Confidential Information or Trade Secrets,
 *      or both, which are the property of UTT Technologies, Inc.
 *      This document may not be copied, reproduced, reduced to any
 *      electronic medium or machine readable form or otherwise duplicated
 *      and the information herein may not be used, disseminated or
 *      otherwise disclosed, except with the prior written consent of
 *      UTT Technologies, Inc.
 */

#line 32 "mibinfr.mdf"

#if (( ! defined( MIBINFR_H ) ) && ( MDF_FRAME_RELAY == FYES ))
#define MIBINFR_H

#include "mibgen.h"
#include "mibglob.h"

    /*
     * How to build the factory instance of this profile.
     */
extern ConstPtr
mibFactoryFrOptions( MibProfileType	mibType,
		     Uint32		info );

    /*
     * Our parameter table is made external as the profile is used
     * within other profiles.
     */
extern const MibFieldComplexParams	frOptionsParams;


    /*
     * FrOptions:
     *
     * Frame Relay configuration options.
     *
     *  frameRelayProfile The name of the frame relay profile of which this
     *                                  connection profile is a DLCI.
     *
     *  dlci The DLCI of this connection.
     *
     *  circuitName The peer frame relay datalink for a FR circuit.
     *
     *  frDirectEnabled Enable the frame relay direct option for this
     *                                  connection.
     *
     *  frDirectName Name of the frame relay profile that will be used for
     *                                  frame-relay-direct routing.
     *
     *  frDirectDlci The DLCI of the frame relay direct connection.
     *
     *  frEnabled Hidden, for answer profile.
     *
     *  fill1 filler.
     */
typedef struct st_frOptions {
#line 82 "mibinfr.mdf"
    char                                frameRelayProfile[ MAX_FR_RELAY_NAME_LEN + 1 ];
#line 88 "mibinfr.mdf"
    Uint16                              dlci;
#line 93 "mibinfr.mdf"
    char                                circuitName[ MAX_FR_RELAY_NAME_LEN + 1 ];
#line 98 "mibinfr.mdf"
    Boolean                             frDirectEnabled;
#line 103 "mibinfr.mdf"
    char                                frDirectName[ MAX_FR_RELAY_NAME_LEN + 2 ];
#line 109 "mibinfr.mdf"
    Uint16                              frDirectDlci;
#line 114 "mibinfr.mdf"
    Boolean                             frEnabled;
#line 120 "mibinfr.mdf"
    char                                fill1;
}
#if ( USERIF & CLI )
__PACK__
#endif
FrOptions;
#line 184 "mibinfr.mdf"

#endif /* (( ! defined( MIBINFR_H ) ) && ( MDF_FRAME_RELAY == FYES ) */

