    /*
     * Notice: file generated by MIBMAKE from mibmonitor.mdf
     * DO NOT EDIT THIS FILE!!!  Edit mibmonitor.mdf
     */
#line 3 "mibmonitor.mdf"
/*
 * $Id: mibmonitor.h,v 1.1.1.1 2011/08/17 11:11:56 brwang Exp $
 *
 *      Copyright (c) 1996 UTT Technologies, Inc.
 *      All rights reserved.
 *      Use of copyright notice does not imply publication.
 *
 *
 *                      CONFIDENTIAL INFORMATION
 *                      ------------------------
 *      This Document contains Confidential Information or Trade Secrets,
 *      or both, which are the property of UTT Technologies, Inc.
 *      This document may not be copied, reproduced, reduced to any
 *      electronic medium or machine readable form or otherwise duplicated
 *      and the information herein may not be used, disseminated or
 *      otherwise disclosed, except with the prior written consent of
 *      UTT Technologies, Inc.
 */

    /*
     * Define the enumerated type MppMonitorType and it's CLI lookup
     * tables.
     */
#line 29 "mibmonitor.mdf"

#if ! defined( MIBMONITOR_H )
#define MIBMONITOR_H

#include "mibgen.h"

#if ( USERIF & CLI )

extern const MibFieldEnumParams	mppMonitorTypeParams;

#endif /* ( USERIF & CLI ) */


    /*
     * MppMonitorType:
     *
     * Defines the direction that can be monitored to determine if bandwidth
     * changes should be made for a session.
     *
     *  MPP_MONITOR_TRANSMIT Monitor the transmit direction only.
     *
     *  MPP_MONITOR_TRANSMIT_RECV Monitor both the transmit and receive
     *                                  directions.
     *
     *  MPP_MONITOR_NONE Turn off link utilization monitoring.
     */
typedef enum MppMonitorType {
#line 58 "mibmonitor.mdf"
    MPP_MONITOR_TRANSMIT,
#line 61 "mibmonitor.mdf"
    MPP_MONITOR_TRANSMIT_RECV,
#line 64 "mibmonitor.mdf"
    MPP_MONITOR_NONE
} MppMonitorType;


static __inline__ Bool
validMppMonitorType (int x)
{
    switch (x) {
#line 58 "mibmonitor.mdf"
    case MPP_MONITOR_TRANSMIT:
#line 61 "mibmonitor.mdf"
    case MPP_MONITOR_TRANSMIT_RECV:
#line 64 "mibmonitor.mdf"
    case MPP_MONITOR_NONE:
        return TRUE;
    default:
        return FALSE;
    }
}
#line 83 "mibmonitor.mdf"

#endif /* MIBMONITOR_H */

