    /*
     * Notice: file generated by MIBMAKE from mibtscl.mdf
     * DO NOT EDIT THIS FILE!!!  Edit mibtscl.mdf
     */
#line 3 "mibtscl.mdf"
/*
 * $Id: mibtscl.h,v 1.1.1.1 2011/08/17 11:11:56 brwang Exp $
 *
 *      Copyright (c) 1996 UTT Technologies, Inc.
 *      All rights reserved.
 *      Use of copyright notice does not imply publication.
 *
 *
 *                      CONFIDENTIAL INFORMATION
 *                      ------------------------
 *      This Document contains Confidential Information or Trade Secrets,
 *      or both, which are the property of UTT Technologies, Inc.
 *      This document may not be copied, reproduced, reduced to any
 *      electronic medium or machine readable form or otherwise duplicated
 *      and the information herein may not be used, disseminated or
 *      otherwise disclosed, except with the prior written consent of
 *      UTT Technologies, Inc.
 */

    /*
     * Define the enumerated type CellLevel and it's CLI lookup
     * tables.
     */
#line 29 "mibtscl.mdf"

#if ! defined( MIBTSCL_H )
#define MIBTSCL_H

#include "mibgen.h"

#if ( USERIF & CLI )

extern const MibFieldEnumParams	cellLevelParams;

#endif /* ( USERIF & CLI ) */


    /*
     * CellLevel:
     *
     * Determine the transmit and receive level for cellular modem connections.
     *
     *  CELL_LEVEL_18 set cellular transmit and receive levels to -18 db
     *
     *  CELL_LEVEL_17 set cellular transmit and receive levels to -17 db
     *
     *  CELL_LEVEL_16 set cellular transmit and receive levels to -16 db
     *
     *  CELL_LEVEL_15 set cellular transmit and receive levels to -15 db
     *
     *  CELL_LEVEL_14 set cellular transmit and receive levels to -14 db
     *
     *  CELL_LEVEL_13 set cellular transmit and receive levels to -13 db
     *
     *  CELL_LEVEL_12 set cellular transmit and receive levels to -12 db
     *
     *  CELL_LEVEL_11 set cellular transmit and receive levels to -11 db
     *
     *  CELL_LEVEL_10 set cellular transmit and receive levels to -10 db
     */
typedef enum CellLevel {
#line 57 "mibtscl.mdf"
    CELL_LEVEL_18,
#line 60 "mibtscl.mdf"
    CELL_LEVEL_17,
#line 63 "mibtscl.mdf"
    CELL_LEVEL_16,
#line 66 "mibtscl.mdf"
    CELL_LEVEL_15,
#line 69 "mibtscl.mdf"
    CELL_LEVEL_14,
#line 72 "mibtscl.mdf"
    CELL_LEVEL_13,
#line 75 "mibtscl.mdf"
    CELL_LEVEL_12,
#line 78 "mibtscl.mdf"
    CELL_LEVEL_11,
#line 81 "mibtscl.mdf"
    CELL_LEVEL_10
} CellLevel;


static __inline__ Bool
validCellLevel (int x)
{
    switch (x) {
#line 57 "mibtscl.mdf"
    case CELL_LEVEL_18:
#line 60 "mibtscl.mdf"
    case CELL_LEVEL_17:
#line 63 "mibtscl.mdf"
    case CELL_LEVEL_16:
#line 66 "mibtscl.mdf"
    case CELL_LEVEL_15:
#line 69 "mibtscl.mdf"
    case CELL_LEVEL_14:
#line 72 "mibtscl.mdf"
    case CELL_LEVEL_13:
#line 75 "mibtscl.mdf"
    case CELL_LEVEL_12:
#line 78 "mibtscl.mdf"
    case CELL_LEVEL_11:
#line 81 "mibtscl.mdf"
    case CELL_LEVEL_10:
        return TRUE;
    default:
        return FALSE;
    }
}
#line 98 "mibtscl.mdf"

#endif /* MIBTSCL_H */

