# Makefile for simpleca programs
# Copyright (C) 2004	Michael Richardson <mcr@xelerance.com>
# 
# This program has a GPL compatible license.
#
# RCSID $Id: Makefile,v 1.1.1.1 2011/08/17 11:10:43 brwang Exp $

OPENSWANSRCDIR?=$(shell cd ../..; pwd)
include ${OPENSWANSRCDIR}/Makefile.inc

PROGRAM=simpleca
EXTRA5PROC=${PROGRAM}.5

include ${srcdir}../Makefile.program

#
# $Log: Makefile,v $
# Revision 1.1.1.1  2011/08/17 11:10:43  brwang
# 3520G start
#
# Revision 1.1.1.1  2011/03/15 05:24:28  lei.minghuan
# import ralink
#
# Revision 1.1.1.1  2009/12/14 12:44:47  brwang
# ralink wlan
#
# Revision 1.1.1.1  2007-10-08 08:01:06  steven
#
#
# Revision 1.2  2004/12/18 18:13:43  mcr
# 	adjusted Makefiles so that ${OBJDIR} builds work.
#
# Revision 1.1  2004/06/17 02:03:27  mcr
#    makefile for simpleca (not yet committed itself)
#
#
#
