#!/bin/bash
#
# RCSID $Id: ttn,v 1.1.1.1 2011/08/17 11:10:45 brwang Exp $
#
# This script is OBSOLETE -- rgb, May 6th, 1998
set +v
insmod ipsec.o
tncfg attach ipsec0 eth2
ifconfig ipsec0 10.2.0.143 up netmask 255.255.0.0
route del 10.2.0.0
route add -net 10.2.0.0 netmask 255.255.0.0 dev ipsec0


#
# $Log: ttn,v $
# Revision 1.1.1.1  2011/08/17 11:10:45  brwang
# 3520G start
#
# Revision 1.1.1.1  2011/03/15 05:24:29  lei.minghuan
# import ralink
#
# Revision 1.1.1.1  2009/12/14 12:44:48  brwang
# ralink wlan
#
# Revision 1.1.1.1  2007-10-08 08:01:05  steven
#
#
# Revision 1.4  2002/04/24 07:36:18  mcr
# Moved from ./klips/test/ji/ttn,v
#
# Revision 1.3  1999/04/06 04:54:36  rgb
# Fix/Add RCSID Id: and Log: bits to make PHMDs happy.  This includes
# patch shell fixes.
#
#
