cvs add ./ctrlpacket.h
cvs add ./ppphdlc.c
cvs add ./README.logwtmp
cvs add ./pptpSrvUp.sh
cvs add ./pptpConnDown.sh
cvs add ./pqueue.c
cvs add ./Makefile.uClinux
cvs add ./pptpmanager.c
cvs add ./inststr.c
cvs add ./bcrelay.c
cvs add ./html
cvs add ./html/setup_pptp_client.html
cvs add ./html/poptop_ads_howto
cvs add ./html/poptop_ads_howto/poptop_ads_howto_5.htm
cvs add ./html/poptop_ads_howto/diagram1.jpg
cvs add ./html/poptop_ads_howto/poptop_ads_howto_3.htm
cvs add ./html/poptop_ads_howto/poptop_ads_howto_a2.htm
cvs add ./html/poptop_ads_howto/poptop_ads_howto_9.htm
cvs add ./html/poptop_ads_howto/poptop_ads_howto_8.htm
cvs add ./html/poptop_ads_howto/poptop_ads_howto_7.htm
cvs add ./html/poptop_ads_howto/poptop_ads_howto_4.htm
cvs add ./html/poptop_ads_howto/test.txt
cvs add ./html/poptop_ads_howto/CVS
cvs add ./html/poptop_ads_howto/CVS/Entries
cvs add ./html/poptop_ads_howto/CVS/Repository
cvs add ./html/poptop_ads_howto/CVS/Root
cvs add ./html/poptop_ads_howto/poptop_ads_howto_11.htm
cvs add ./html/poptop_ads_howto/poptop_ads_howto_12.htm
cvs add ./html/poptop_ads_howto/poptop_ads_howto_10.htm
cvs add ./html/poptop_ads_howto/poptop_ads_howto_6.htm
cvs add ./html/poptop_ads_howto/poptop_ads_howto_2.htm
cvs add ./html/poptop_ads_howto/poptop_ads_howto_6a.htm
cvs add ./html/poptop_ads_howto/poptop_ads_howto_1.htm
cvs add ./html/poptop_ads_howto/poptop_ads_howto_a1.htm
cvs add ./html/HOWTO-PoPToP.txt
cvs add ./html/CVS
cvs add ./html/CVS/Entries
cvs add ./html/CVS/Repository
cvs add ./html/CVS/Root
cvs add ./README.inetd
cvs add ./pptpd-prof.c
cvs add ./compat.c
cvs add ./Makefile.am
cvs add ./configfile.c
cvs add ./configure.in
cvs add ./pptpd.c
cvs add ./our_syslog.h
cvs add ./samples
cvs add ./samples/options.pptpd
cvs add ./samples/chap-secrets
cvs add ./samples/pptpd.conf
cvs add ./Makefile
cvs add ./Makefile.in
cvs add ./debian
cvs add ./debian/dirs
cvs add ./debian/config
cvs add ./debian/examples
cvs add ./debian/pptpd-options
cvs add ./debian/changelog
cvs add ./debian/po
cvs add ./debian/po/POTFILES.in
cvs add ./debian/po/pt_BR.po
cvs add ./debian/po/templates.pot
cvs add ./debian/po/fr.po
cvs add ./debian/copyright
cvs add ./debian/rules
cvs add ./debian/README.debian
cvs add ./debian/control
cvs add ./debian/docs
cvs add ./debian/pptpd.conf
cvs add ./debian/pptpd.init
cvs add ./debian/templates
cvs add ./debian/conffiles
cvs add ./debian/pptpdconfig.pl
cvs add ./inststr.h
cvs add ./stamp-h1
cvs add ./NEWS
cvs add ./pptpctrl.h
cvs add ./ChangeLog
cvs add ./defaults.h
cvs add ./pptpgre.c
cvs add ./pptpd.8
cvs add ./pqueue.h
cvs add ./pptpSrvAccDelAll.sh
cvs add ./README
cvs add ./our_getopt.h
cvs add ./reconf
cvs add ./plugins
cvs add ./plugins/Makefile
cvs add ./plugins/patchlevel.h
cvs add ./plugins/pptpd-logwtmp.c
cvs add ./plugins/pppd.h
cvs add ./pptpd.spec
cvs add ./missing
cvs add ./pptpctrl.8
cvs add ./README.portslave
cvs add ./configure
cvs add ./config.log
cvs add ./pptpgre.h
cvs add ./acconfig.h
cvs add ./pptpd.conf.5
cvs add ./config.embed.h
cvs add ./compat.h
cvs add ./ctrlpacket.c
cvs add ./mkinstalldirs
cvs add ./ppphdlc.h
cvs add ./README.bcrelay
cvs add ./version
cvs add ./pptpd.init
cvs add ./pptpctrl.c
cvs add ./tools
cvs add ./tools/pptp-portslave
cvs add ./tools/vpnuser
cvs add ./tools/vpnstats.pl
cvs add ./tools/vpnstats
cvs add ./pptpd-logwtmp.so
cvs add ./getopt1.c
cvs add ./configfile.h
cvs add ./pptpdefs.h
cvs add ./README.cvs
cvs add ./.sgbuilt_user
cvs add ./README.slirp
cvs add ./pptpSrvDown.sh
cvs add ./pptpmanager.h
cvs add ./TODO
cvs add ./makepackage
cvs add ./INSTALL
cvs add ./pptpSrvAccDel.sh
cvs add ./pptpSrvGloConf.sh
cvs add ./getopt.c
cvs add ./config.h
cvs add ./install-sh
cvs add ./tmp.sh
cvs add ./config.status
cvs add ./pptpConnUp.sh
cvs add ./AUTHORS
cvs add ./aclocal.m4
cvs add ./config.h.in
cvs add ./pptpSrvAccAdd.sh
cvs add ./COPYING
