
#
#added by brwang
#
#
SUB_DIR := $(ROOTDIR)/uttShareHead/config
EXTRA_CFLAGS  += -I$(SUB_DIR)
obj-$(CONFIG_PERFORMANCE_OPTIMIZATION) 	+= sharemem.o
obj-$(CONFIG_UTT_TIME_GRP) 			+= time_set/
obj-$(CONFIG_UTT_NF_DNS_FILTER) 		+= dns_filter/
obj-$(CONFIG_PERFORMANCE_OPTIMIZATION) 	+= limit/

#obj-y	+= config.o
#obj-y	+= user_info.o
