/* This file is automatically generated by configure.  Do not modify by hand. */
  if (should_init("snmp_mib")) init_snmp_mib();
  if (should_init("system_mib")) init_system_mib();
  if (should_init("sysORTable")) init_sysORTable();
  if (should_init("interfaces")) init_interfaces();
  if (should_init("vacm_vars")) init_vacm_vars();
  if (should_init("snmpEngine")) init_snmpEngine();
  if (should_init("snmpMPDStats")) init_snmpMPDStats();
  if (should_init("usmStats")) init_usmStats();
  if (should_init("usmUser")) init_usmUser();
  if (should_init("vacm_context")) init_vacm_context();
  if (should_init("at")) init_at();
  if (should_init("ip")) init_ip();
  if (should_init("var_route")) init_var_route();
  
  if (should_init("hr_system")) init_hr_system();
  if (should_init("hr_storage")) init_hr_storage();
  if (should_init("hr_device")) init_hr_device();
  if (should_init("hr_other")) init_hr_other();
  if (should_init("hr_proc")) init_hr_proc();
  if (should_init("hr_network")) init_hr_network();
  if (should_init("hr_print")) init_hr_print();
  if (should_init("hr_disk")) init_hr_disk();
  if (should_init("hr_partition")) init_hr_partition();
  if (should_init("hr_filesys")) init_hr_filesys();
  if (should_init("hr_swrun")) init_hr_swrun();
  if (should_init("hr_swinst")) init_hr_swinst();
  
  if (should_init("hw_mem")) init_hw_mem();
  if (should_init("cpu")) init_cpu();
  if (should_init("cpu_linux")) init_cpu_linux();

/*ucd-snmp*/
  if (should_init("loadave")) init_loadave();
  if (should_init("vmstat")) init_vmstat();

