all:

romfs:
	$(ROMFSINST)  /usr/bin/elink.lua
	$(ROMFSINST)  -d /usr/local/lib/lua/5.3/base64.lua
	$(ROMFSINST)  -d /usr/local/lib/lua/5.3/set.lua
	$(ROMFSINST)  -d /usr/local/lib/lua/5.3/get.lua
	$(ROMFSINST)  -d /etc_ro/Wireless/default5g.dat
	$(ROMFSINST)  -d /etc_ro/Wireless/default2g.dat


