    /*
     * Notice: file generated by MIBMAKE from mibfwall.mdf
     * DO NOT EDIT THIS FILE!!!  Edit mibfwall.mdf
     */
#line 2 "mibfwall.mdf"
/*
 * SCCS ID: $Id: mibfwall.h,v 1.1.1.1 2011/08/17 11:11:56 brwang Exp $
 *
 *      Copyright (c) 1996 UTT Technologies, Inc.
 *      All rights reserved.
 *      Use of copyright notice does not imply publication.
 *
 *
 *                      CONFIDENTIAL INFORMATION
 *                      ------------------------
 *      This Document contains Confidential Information or Trade Secrets,
 *      or both, which are the property of UTT Technologies, Inc.
 *      This document may not be copied, reproduced, reduced to any
 *      electronic medium or machine readable form or otherwise duplicated
 *      and the information herein may not be used, disseminated or
 *      otherwise disclosed, except with the prior written consent of
 *      UTT Technologies, Inc.
 */

#line 24 "mibfwall.mdf"

#if ! defined( MIBFWALL_H )
#define MIBFWALL_H

#if ( FIREWALLS == FYES )

extern const char* const              mibProfFwall;

#line 57 "mibfwall.mdf"

#define MAX_FWDATA_LEN		4096

#define FWALL_COMPRESSED	1


    /*
     *	fw_data[ MAX_FWDATA_LEN ];
     *	verlen|cksum|data
     *	2      2     ....
     *
     * length fits in 12 bits, so it can never exceed 4095 bytes. 
     * others for types
     */
 
    /*
     * FwallProfile:
     *
     * Configure parameters of a FireWall.
     *
     *  fw_name/name Descriptive name for this firewall.
     *
     *  fw_version The version number of software required to load this
     *                                  firewall.
     *
     *  fw_data The actual contents of the FireWall.
     *
     *  fw_extLink Link to an extension firewall profile.
     */
typedef struct FwallProfile {
#line 91 "mibfwall.mdf"
//  char                                fw_name[ MAX_FWNAME_LEN + 1 ];
    char                                name[ MAX_PROFILE_NAME_LENGTH + 1 ];
    Boolean                             active; 
    char                                description[MAX_PROFILE_NAME_LENGTH+1];
    Uint32				creTm;
    Word                                fw_type;
#line 96 "mibfwall.mdf"
    Word                                fw_version;
#line 101 "mibfwall.mdf"
    char                                fw_data[ MAX_FWDATA_LEN ];
#line 106 "mibfwall.mdf"
    char                                fw_extLink[ MAX_FWNAME_LEN + 1 ];
}
#if ( USERIF & CLI )
__PACK__
#endif
FwallProfile;
#line 116 "mibfwall.mdf"

 	/* The field ID of the Index Field for this profile. */
#define	MIB_FW_INT_INDEX_FIELD	1

extern const FwallProfile*
mibFactoryFwallProfile( MibProfileType        mibType,
                      ConstPtr        mibIndex,
                      Int             mibIndexLen );

#line 192 "mibfwall.mdf"

#endif /* MDF_FIREWALLS == FYES */

#endif /* MIBFWALL_H */

